rem kevin shibata
rem kkshibat@calpoly.edu
INSERT INTO CarName VALUES (1,'chevrolet','chevrolet chevelle malibu');
INSERT INTO CarName VALUES (2,'buick','buick skylark 320');
INSERT INTO CarName VALUES (3,'plymouth','plymouth satellite');
INSERT INTO CarName VALUES (4,'amc','amc rebel sst');
INSERT INTO CarName VALUES (5,'ford','ford torino');
INSERT INTO CarName VALUES (6,'ford','ford galaxie 500');
INSERT INTO CarName VALUES (7,'chevrolet','chevrolet impala');
INSERT INTO CarName VALUES (8,'plymouth','plymouth fury iii');
INSERT INTO CarName VALUES (9,'pontiac','pontiac catalina');
INSERT INTO CarName VALUES (10,'amc','amc ambassador dpl');
INSERT INTO CarName VALUES (11,'citroen','citroen ds-21 pallas');
INSERT INTO CarName VALUES (12,'chevrolet','chevrolet chevelle concours (sw)');
INSERT INTO CarName VALUES (13,'ford','ford torino (sw)');
INSERT INTO CarName VALUES (14,'plymouth','plymouth satellite (sw)');
INSERT INTO CarName VALUES (15,'amc','amc rebel sst (sw)');
INSERT INTO CarName VALUES (16,'dodge','dodge challenger se');
INSERT INTO CarName VALUES (17,'plymouth','plymouth cuda 340');
INSERT INTO CarName VALUES (18,'ford','ford mustang boss 302');
INSERT INTO CarName VALUES (19,'chevrolet','chevrolet monte carlo');
INSERT INTO CarName VALUES (20,'buick','buick estate wagon (sw)');
INSERT INTO CarName VALUES (21,'toyota','toyota corona mark ii');
INSERT INTO CarName VALUES (22,'plymouth','plymouth duster');
INSERT INTO CarName VALUES (23,'amc','amc hornet');
INSERT INTO CarName VALUES (24,'ford','ford maverick');
INSERT INTO CarName VALUES (25,'datsun','datsun pl510');
INSERT INTO CarName VALUES (26,'volkswagen','volkswagen 1131 deluxe sedan');
INSERT INTO CarName VALUES (27,'peugeot','peugeot 504');
INSERT INTO CarName VALUES (28,'audi','audi 100 ls');
INSERT INTO CarName VALUES (29,'saab','saab 99e');
INSERT INTO CarName VALUES (30,'bmw','bmw 2002');
INSERT INTO CarName VALUES (31,'amc','amc gremlin');
INSERT INTO CarName VALUES (32,'ford','ford f250');
INSERT INTO CarName VALUES (33,'chevrolet','chevy c20');
INSERT INTO CarName VALUES (34,'dodge','dodge d200');
INSERT INTO CarName VALUES (35,'hi','hi 1200d');
INSERT INTO CarName VALUES (36,'datsun','datsun pl510');
INSERT INTO CarName VALUES (37,'chevrolet','chevrolet vega 2300');
INSERT INTO CarName VALUES (38,'toyota','toyota corona');
INSERT INTO CarName VALUES (39,'ford','ford pinto');
INSERT INTO CarName VALUES (40,'volkswagen','volkswagen super beetle 117');
INSERT INTO CarName VALUES (41,'amc','amc gremlin');
INSERT INTO CarName VALUES (42,'plymouth','plymouth satellite custom');
INSERT INTO CarName VALUES (43,'chevrolet','chevrolet chevelle malibu');
INSERT INTO CarName VALUES (44,'ford','ford torino 500');
INSERT INTO CarName VALUES (45,'amc','amc matador');
INSERT INTO CarName VALUES (46,'chevrolet','chevrolet impala');
INSERT INTO CarName VALUES (47,'pontiac','pontiac catalina brougham');
INSERT INTO CarName VALUES (48,'ford','ford galaxie 500');
INSERT INTO CarName VALUES (49,'plymouth','plymouth fury iii');
INSERT INTO CarName VALUES (50,'dodge','dodge monaco (sw)');
INSERT INTO CarName VALUES (51,'ford','ford country squire (sw)');
INSERT INTO CarName VALUES (52,'pontiac','pontiac safari (sw)');
INSERT INTO CarName VALUES (53,'amc','amc hornet sportabout (sw)');
INSERT INTO CarName VALUES (54,'chevrolet','chevrolet vega (sw)');
INSERT INTO CarName VALUES (55,'pontiac','pontiac firebird');
INSERT INTO CarName VALUES (56,'ford','ford mustang');
INSERT INTO CarName VALUES (57,'mercury','mercury capri 2000');
INSERT INTO CarName VALUES (58,'opel','opel 1900');
INSERT INTO CarName VALUES (59,'peugeot','peugeot 304');
INSERT INTO CarName VALUES (60,'fiat','fiat 124b');
INSERT INTO CarName VALUES (61,'toyota','toyota corolla 1200');
INSERT INTO CarName VALUES (62,'datsun','datsun 1200');
INSERT INTO CarName VALUES (63,'volkswagen','volkswagen model 111');
INSERT INTO CarName VALUES (64,'plymouth','plymouth cricket');
INSERT INTO CarName VALUES (65,'toyota','toyota corona hardtop');
INSERT INTO CarName VALUES (66,'dodge','dodge colt hardtop');
INSERT INTO CarName VALUES (67,'volkswagen','volkswagen type 3');
INSERT INTO CarName VALUES (68,'chevrolet','chevrolet vega');
INSERT INTO CarName VALUES (69,'ford','ford pinto runabout');
INSERT INTO CarName VALUES (70,'chevrolet','chevrolet impala');
INSERT INTO CarName VALUES (71,'pontiac','pontiac catalina');
INSERT INTO CarName VALUES (72,'plymouth','plymouth fury iii');
INSERT INTO CarName VALUES (73,'ford','ford galaxie 500');
INSERT INTO CarName VALUES (74,'amc','amc ambassador sst');
INSERT INTO CarName VALUES (75,'mercury','mercury marquis');
INSERT INTO CarName VALUES (76,'buick','buick lesabre custom');
INSERT INTO CarName VALUES (77,'oldsmobile','oldsmobile delta 88 royale');
INSERT INTO CarName VALUES (78,'chrysler','chrysler newport royal');
INSERT INTO CarName VALUES (79,'mazda','mazda rx2 coupe');
INSERT INTO CarName VALUES (80,'amc','amc matador (sw)');
INSERT INTO CarName VALUES (81,'chevrolet','chevrolet chevelle concours (sw)');
INSERT INTO CarName VALUES (82,'ford','ford gran torino (sw)');
INSERT INTO CarName VALUES (83,'plymouth','plymouth satellite custom (sw)');
INSERT INTO CarName VALUES (84,'volvo','volvo 145e (sw)');
INSERT INTO CarName VALUES (85,'volkswagen','volkswagen 411 (sw)');
INSERT INTO CarName VALUES (86,'peugeot','peugeot 504 (sw)');
INSERT INTO CarName VALUES (87,'renault','renault 12 (sw)');
INSERT INTO CarName VALUES (88,'ford','ford pinto (sw)');
INSERT INTO CarName VALUES (89,'datsun','datsun 510 (sw)');
INSERT INTO CarName VALUES (90,'toyota','toyota corona mark ii (sw)');
INSERT INTO CarName VALUES (91,'dodge','dodge colt (sw)');
INSERT INTO CarName VALUES (92,'toyota','toyota corolla 1600 (sw)');
INSERT INTO CarName VALUES (93,'buick','buick century 350');
INSERT INTO CarName VALUES (94,'amc','amc matador');
INSERT INTO CarName VALUES (95,'chevrolet','chevrolet malibu');
INSERT INTO CarName VALUES (96,'ford','ford gran torino');
INSERT INTO CarName VALUES (97,'dodge','dodge coronet custom');
INSERT INTO CarName VALUES (98,'mercury','mercury marquis brougham');
INSERT INTO CarName VALUES (99,'chevrolet','chevrolet caprice classic');
INSERT INTO CarName VALUES (100,'ford','ford ltd');
INSERT INTO CarName VALUES (101,'plymouth','plymouth fury gran sedan');
INSERT INTO CarName VALUES (102,'chrysler','chrysler new yorker brougham');
INSERT INTO CarName VALUES (103,'buick','buick electra 225 custom');
INSERT INTO CarName VALUES (104,'amc','amc ambassador brougham');
INSERT INTO CarName VALUES (105,'plymouth','plymouth valiant');
INSERT INTO CarName VALUES (106,'chevrolet','chevrolet nova custom');
INSERT INTO CarName VALUES (107,'amc','amc hornet');
INSERT INTO CarName VALUES (108,'ford','ford maverick');
INSERT INTO CarName VALUES (109,'plymouth','plymouth duster');
INSERT INTO CarName VALUES (110,'volkswagen','volkswagen super beetle');
INSERT INTO CarName VALUES (111,'chevrolet','chevrolet impala');
INSERT INTO CarName VALUES (112,'ford','ford country');
INSERT INTO CarName VALUES (113,'plymouth','plymouth custom suburb');
INSERT INTO CarName VALUES (114,'oldsmobile','oldsmobile vista cruiser');
INSERT INTO CarName VALUES (115,'amc','amc gremlin');
INSERT INTO CarName VALUES (116,'toyota','toyota carina');
INSERT INTO CarName VALUES (117,'chevrolet','chevrolet vega');
INSERT INTO CarName VALUES (118,'datsun','datsun 610');
INSERT INTO CarName VALUES (119,'mazda','mazda rx3');
INSERT INTO CarName VALUES (120,'ford','ford pinto');
INSERT INTO CarName VALUES (121,'mercury','mercury capri v6');
INSERT INTO CarName VALUES (122,'fiat','fiat 124 sport coupe');
INSERT INTO CarName VALUES (123,'chevrolet','chevrolet monte carlo s');
INSERT INTO CarName VALUES (124,'pontiac','pontiac grand prix');
INSERT INTO CarName VALUES (125,'fiat','fiat 128');
INSERT INTO CarName VALUES (126,'opel','opel manta');
INSERT INTO CarName VALUES (127,'audi','audi 100ls');
INSERT INTO CarName VALUES (128,'volvo','volvo 144ea');
INSERT INTO CarName VALUES (129,'dodge','dodge dart custom');
INSERT INTO CarName VALUES (130,'saab','saab 99le');
INSERT INTO CarName VALUES (131,'toyota','toyota mark ii');
INSERT INTO CarName VALUES (132,'oldsmobile','oldsmobile omega');
INSERT INTO CarName VALUES (133,'plymouth','plymouth duster');
INSERT INTO CarName VALUES (134,'ford','ford maverick');
INSERT INTO CarName VALUES (135,'amc','amc hornet');
INSERT INTO CarName VALUES (136,'chevrolet','chevrolet nova');
INSERT INTO CarName VALUES (137,'datsun','datsun b210');
INSERT INTO CarName VALUES (138,'ford','ford pinto');
INSERT INTO CarName VALUES (139,'toyota','toyota corolla 1200');
INSERT INTO CarName VALUES (140,'chevrolet','chevrolet vega');
INSERT INTO CarName VALUES (141,'chevrolet','chevrolet chevelle malibu classic');
INSERT INTO CarName VALUES (142,'amc','amc matador');
INSERT INTO CarName VALUES (143,'plymouth','plymouth satellite sebring');
INSERT INTO CarName VALUES (144,'ford','ford gran torino');
INSERT INTO CarName VALUES (145,'buick','buick century luxus (sw)');
INSERT INTO CarName VALUES (146,'dodge','dodge coronet custom (sw)');
INSERT INTO CarName VALUES (147,'ford','ford gran torino (sw)');
INSERT INTO CarName VALUES (148,'amc','amc matador (sw)');
INSERT INTO CarName VALUES (149,'audi','audi fox');
INSERT INTO CarName VALUES (150,'volkswagen','volkswagen dasher');
INSERT INTO CarName VALUES (151,'opel','opel manta');
INSERT INTO CarName VALUES (152,'toyota','toyota corona');
INSERT INTO CarName VALUES (153,'datsun','datsun 710');
INSERT INTO CarName VALUES (154,'dodge','dodge colt');
INSERT INTO CarName VALUES (155,'fiat','fiat 128');
INSERT INTO CarName VALUES (156,'fiat','fiat 124 tc');
INSERT INTO CarName VALUES (157,'honda','honda civic');
INSERT INTO CarName VALUES (158,'subaru','subaru');
INSERT INTO CarName VALUES (159,'fiat','fiat x1.9');
INSERT INTO CarName VALUES (160,'plymouth','plymouth valiant custom');
INSERT INTO CarName VALUES (161,'chevrolet','chevrolet nova');
INSERT INTO CarName VALUES (162,'mercury','mercury monarch');
INSERT INTO CarName VALUES (163,'ford','ford maverick');
INSERT INTO CarName VALUES (164,'pontiac','pontiac catalina');
INSERT INTO CarName VALUES (165,'chevrolet','chevrolet bel air');
INSERT INTO CarName VALUES (166,'plymouth','plymouth grand fury');
INSERT INTO CarName VALUES (167,'ford','ford ltd');
INSERT INTO CarName VALUES (168,'buick','buick century');
INSERT INTO CarName VALUES (169,'chevrolet','chevrolet chevelle malibu');
INSERT INTO CarName VALUES (170,'amc','amc matador');
INSERT INTO CarName VALUES (171,'plymouth','plymouth fury');
INSERT INTO CarName VALUES (172,'buick','buick skyhawk');
INSERT INTO CarName VALUES (173,'chevrolet','chevrolet monza 2+2');
INSERT INTO CarName VALUES (174,'ford','ford mustang ii');
INSERT INTO CarName VALUES (175,'toyota','toyota corolla');
INSERT INTO CarName VALUES (176,'ford','ford pinto');
INSERT INTO CarName VALUES (177,'amc','amc gremlin');
INSERT INTO CarName VALUES (178,'pontiac','pontiac astro');
INSERT INTO CarName VALUES (179,'toyota','toyota corona');
INSERT INTO CarName VALUES (180,'volkswagen','volkswagen dasher');
INSERT INTO CarName VALUES (181,'datsun','datsun 710');
INSERT INTO CarName VALUES (182,'ford','ford pinto');
INSERT INTO CarName VALUES (183,'volkswagen','volkswagen rabbit');
INSERT INTO CarName VALUES (184,'amc','amc pacer');
INSERT INTO CarName VALUES (185,'audi','audi 100ls');
INSERT INTO CarName VALUES (186,'peugeot','peugeot 504');
INSERT INTO CarName VALUES (187,'volvo','volvo 244dl');
INSERT INTO CarName VALUES (188,'saab','saab 99le');
INSERT INTO CarName VALUES (189,'honda','honda civic cvcc');
INSERT INTO CarName VALUES (190,'fiat','fiat 131');
INSERT INTO CarName VALUES (191,'opel','opel 1900');
INSERT INTO CarName VALUES (192,'capri','capri ii');
INSERT INTO CarName VALUES (193,'dodge','dodge colt');
INSERT INTO CarName VALUES (194,'renault','renault 12tl');
INSERT INTO CarName VALUES (195,'chevrolet','chevrolet chevelle malibu classic');
INSERT INTO CarName VALUES (196,'dodge','dodge coronet brougham');
INSERT INTO CarName VALUES (197,'amc','amc matador');
INSERT INTO CarName VALUES (198,'ford','ford gran torino');
INSERT INTO CarName VALUES (199,'plymouth','plymouth valiant');
INSERT INTO CarName VALUES (200,'chevrolet','chevrolet nova');
INSERT INTO CarName VALUES (201,'ford','ford maverick');
INSERT INTO CarName VALUES (202,'amc','amc hornet');
INSERT INTO CarName VALUES (203,'chevrolet','chevrolet chevette');
INSERT INTO CarName VALUES (204,'chevrolet','chevrolet woody');
INSERT INTO CarName VALUES (205,'volkswagen','vw rabbit');
INSERT INTO CarName VALUES (206,'honda','honda civic');
INSERT INTO CarName VALUES (207,'dodge','dodge aspen se');
INSERT INTO CarName VALUES (208,'ford','ford granada ghia');
INSERT INTO CarName VALUES (209,'pontiac','pontiac ventura sj');
INSERT INTO CarName VALUES (210,'amc','amc pacer d/l');
INSERT INTO CarName VALUES (211,'volkswagen','volkswagen rabbit');
INSERT INTO CarName VALUES (212,'datsun','datsun b-210');
INSERT INTO CarName VALUES (213,'toyota','toyota corolla');
INSERT INTO CarName VALUES (214,'ford','ford pinto');
INSERT INTO CarName VALUES (215,'volvo','volvo 245');
INSERT INTO CarName VALUES (216,'plymouth','plymouth volare premier v8');
INSERT INTO CarName VALUES (217,'peugeot','peugeot 504');
INSERT INTO CarName VALUES (218,'toyota','toyota mark ii');
INSERT INTO CarName VALUES (219,'mercedes-benz','mercedes-benz 280s');
INSERT INTO CarName VALUES (220,'cadillac','cadillac seville');
INSERT INTO CarName VALUES (221,'chevrolet','chevy c10');
INSERT INTO CarName VALUES (222,'ford','ford f108');
INSERT INTO CarName VALUES (223,'dodge','dodge d100');
INSERT INTO CarName VALUES (224,'honda','honda accord cvcc');
INSERT INTO CarName VALUES (225,'buick','buick opel isuzu deluxe');
INSERT INTO CarName VALUES (226,'renault','renault 5 gtl');
INSERT INTO CarName VALUES (227,'plymouth','plymouth arrow gs');
INSERT INTO CarName VALUES (228,'datsun','datsun f-10 hatchback');
INSERT INTO CarName VALUES (229,'chevrolet','chevrolet caprice classic');
INSERT INTO CarName VALUES (230,'oldsmobile','oldsmobile cutlass supreme');
INSERT INTO CarName VALUES (231,'dodge','dodge monaco brougham');
INSERT INTO CarName VALUES (232,'mercury','mercury cougar brougham');
INSERT INTO CarName VALUES (233,'chevrolet','chevrolet concours');
INSERT INTO CarName VALUES (234,'buick','buick skylark');
INSERT INTO CarName VALUES (235,'plymouth','plymouth volare custom');
INSERT INTO CarName VALUES (236,'ford','ford granada');
INSERT INTO CarName VALUES (237,'pontiac','pontiac grand prix lj');
INSERT INTO CarName VALUES (238,'chevrolet','chevrolet monte carlo landau');
INSERT INTO CarName VALUES (239,'chrysler','chrysler cordoba');
INSERT INTO CarName VALUES (240,'ford','ford thunderbird');
INSERT INTO CarName VALUES (241,'volkswagen','volkswagen rabbit custom');
INSERT INTO CarName VALUES (242,'pontiac','pontiac sunbird coupe');
INSERT INTO CarName VALUES (243,'toyota','toyota corolla liftback');
INSERT INTO CarName VALUES (244,'ford','ford mustang ii 2+2');
INSERT INTO CarName VALUES (245,'chevrolet','chevrolet chevette');
INSERT INTO CarName VALUES (246,'dodge','dodge colt m/m');
INSERT INTO CarName VALUES (247,'subaru','subaru dl');
INSERT INTO CarName VALUES (248,'volkswagen','volkswagen dasher');
INSERT INTO CarName VALUES (249,'datsun','datsun 810');
INSERT INTO CarName VALUES (250,'bmw','bmw 320i');
INSERT INTO CarName VALUES (251,'mazda','mazda rx-4');
INSERT INTO CarName VALUES (252,'volkswagen','volkswagen rabbit custom diesel');
INSERT INTO CarName VALUES (253,'ford','ford fiesta');
INSERT INTO CarName VALUES (254,'mazda','mazda glc deluxe');
INSERT INTO CarName VALUES (255,'datsun','datsun b210 gx');
INSERT INTO CarName VALUES (256,'honda','honda civic cvcc');
INSERT INTO CarName VALUES (257,'oldsmobile','oldsmobile cutlass salon brougham');
INSERT INTO CarName VALUES (258,'dodge','dodge diplomat');
INSERT INTO CarName VALUES (259,'mercury','mercury monarch ghia');
INSERT INTO CarName VALUES (260,'pontiac','pontiac phoenix lj');
INSERT INTO CarName VALUES (261,'chevrolet','chevrolet malibu');
INSERT INTO CarName VALUES (262,'ford','ford fairmont (auto)');
INSERT INTO CarName VALUES (263,'ford','ford fairmont (man)');
INSERT INTO CarName VALUES (264,'plymouth','plymouth volare');
INSERT INTO CarName VALUES (265,'amc','amc concord');
INSERT INTO CarName VALUES (266,'buick','buick century special');
INSERT INTO CarName VALUES (267,'mercury','mercury zephyr');
INSERT INTO CarName VALUES (268,'dodge','dodge aspen');
INSERT INTO CarName VALUES (269,'amc','amc concord d/l');
INSERT INTO CarName VALUES (270,'chevrolet','chevrolet monte carlo landau');
INSERT INTO CarName VALUES (271,'buick','buick regal sport coupe (turbo)');
INSERT INTO CarName VALUES (272,'ford','ford futura');
INSERT INTO CarName VALUES (273,'dodge','dodge magnum xe');
INSERT INTO CarName VALUES (274,'chevrolet','chevrolet chevette');
INSERT INTO CarName VALUES (275,'toyota','toyota corona');
INSERT INTO CarName VALUES (276,'datsun','datsun 510');
INSERT INTO CarName VALUES (277,'dodge','dodge omni');
INSERT INTO CarName VALUES (278,'toyota','toyota celica gt liftback');
INSERT INTO CarName VALUES (279,'plymouth','plymouth sapporo');
INSERT INTO CarName VALUES (280,'oldsmobile','oldsmobile starfire sx');
INSERT INTO CarName VALUES (281,'datsun','datsun 200-sx');
INSERT INTO CarName VALUES (282,'audi','audi 5000');
INSERT INTO CarName VALUES (283,'volvo','volvo 264gl');
INSERT INTO CarName VALUES (284,'saab','saab 99gle');
INSERT INTO CarName VALUES (285,'peugeot','peugeot 604sl');
INSERT INTO CarName VALUES (286,'volkswagen','volkswagen scirocco');
INSERT INTO CarName VALUES (287,'honda','honda accord lx');
INSERT INTO CarName VALUES (288,'pontiac','pontiac lemans v6');
INSERT INTO CarName VALUES (289,'mercury','mercury zephyr 6');
INSERT INTO CarName VALUES (290,'ford','ford fairmont 4');
INSERT INTO CarName VALUES (291,'amc','amc concord dl 6');
INSERT INTO CarName VALUES (292,'dodge','dodge aspen 6');
INSERT INTO CarName VALUES (293,'chevrolet','chevrolet caprice classic');
INSERT INTO CarName VALUES (294,'ford','ford ltd landau');
INSERT INTO CarName VALUES (295,'mercury','mercury grand marquis');
INSERT INTO CarName VALUES (296,'dodge','dodge st. regis');
INSERT INTO CarName VALUES (297,'buick','buick estate wagon (sw)');
INSERT INTO CarName VALUES (298,'ford','ford country squire (sw)');
INSERT INTO CarName VALUES (299,'chevrolet','chevrolet malibu classic (sw)');
INSERT INTO CarName VALUES (300,'chrysler','chrysler lebaron town @ country (sw)');
INSERT INTO CarName VALUES (301,'volkswagen','vw rabbit custom');
INSERT INTO CarName VALUES (302,'mazda', 'mazda glc deluxe');
INSERT INTO CarName VALUES (303,'dodge','dodge colt hatchback custom');
INSERT INTO CarName VALUES (304,'amc','amc spirit dl');
INSERT INTO CarName VALUES (305,'mercedes','mercedes benz 300d');
INSERT INTO CarName VALUES (306,'cadillac','cadillac eldorado');
INSERT INTO CarName VALUES (307,'peugeot','peugeot 504');
INSERT INTO CarName VALUES (308,'oldsmobile','oldsmobile cutlass salon brougham');
INSERT INTO CarName VALUES (309,'plymouth','plymouth horizon');
INSERT INTO CarName VALUES (310,'plymouth','plymouth horizon tc3');
INSERT INTO CarName VALUES (311,'datsun','datsun 210');
INSERT INTO CarName VALUES (312,'fiat','fiat strada custom');
INSERT INTO CarName VALUES (313,'buick','buick skylark limited');
INSERT INTO CarName VALUES (314,'chevrolet','chevrolet citation');
INSERT INTO CarName VALUES (315,'oldsmobile','oldsmobile omega brougham');
INSERT INTO CarName VALUES (316,'pontiac','pontiac phoenix');
INSERT INTO CarName VALUES (317,'volkswagen','vw rabbit');
INSERT INTO CarName VALUES (318,'toyota','toyota corolla tercel');
INSERT INTO CarName VALUES (319,'chevrolet','chevrolet chevette');
INSERT INTO CarName VALUES (320,'datsun','datsun 310');
INSERT INTO CarName VALUES (321,'chevrolet','chevrolet citation');
INSERT INTO CarName VALUES (322,'ford','ford fairmont');
INSERT INTO CarName VALUES (323,'amc','amc concord');
INSERT INTO CarName VALUES (324,'dodge','dodge aspen');
INSERT INTO CarName VALUES (325,'audi','audi 4000');
INSERT INTO CarName VALUES (326,'toyota','toyota corona liftback');
INSERT INTO CarName VALUES (327,'mazda','mazda 626');
INSERT INTO CarName VALUES (328,'datsun','datsun 510 hatchback');
INSERT INTO CarName VALUES (329,'toyota','toyota corolla');
INSERT INTO CarName VALUES (330,'mazda','mazda glc');
INSERT INTO CarName VALUES (331,'dodge','dodge colt');
INSERT INTO CarName VALUES (332,'datsun','datsun 210');
INSERT INTO CarName VALUES (333,'volkswagen','vw rabbit c (diesel)');
INSERT INTO CarName VALUES (334,'volkswagen','vw dasher (diesel)');
INSERT INTO CarName VALUES (335,'audi','audi 5000s (diesel)');
INSERT INTO CarName VALUES (336,'mercedes-benz','mercedes-benz 240d');
INSERT INTO CarName VALUES (337,'honda','honda civic 1500 gl');
INSERT INTO CarName VALUES (338,'renault','renault lecar deluxe');
INSERT INTO CarName VALUES (339,'subaru','subaru dl');
INSERT INTO CarName VALUES (340, 'volkswagen','volkswagen rabbit');
INSERT INTO CarName VALUES (341,'datsun','datsun 280-zx');
INSERT INTO CarName VALUES (342,'mazda','mazda rx-7 gs');
INSERT INTO CarName VALUES (343,'triumph','triumph tr7 coupe');
INSERT INTO CarName VALUES (344,'ford','ford mustang cobra');
INSERT INTO CarName VALUES (345,'honda','honda accord');
INSERT INTO CarName VALUES (346,'plymouth','plymouth reliant');
INSERT INTO CarName VALUES (347,'buick','buick skylark');
INSERT INTO CarName VALUES (348,'dodge','dodge aries wagon (sw)');
INSERT INTO CarName VALUES (349,'chevrolet','chevrolet citation');
INSERT INTO CarName VALUES (350,'plymouth','plymouth reliant');
INSERT INTO CarName VALUES (351,'toyota','toyota starlet');
INSERT INTO CarName VALUES (352,'plymouth','plymouth champ');
INSERT INTO CarName VALUES (353,'honda','honda civic 1300');
INSERT INTO CarName VALUES (354,'subaru','subaru');
INSERT INTO CarName VALUES (355,'datsun','datsun 210 mpg');
INSERT INTO CarName VALUES (356,'toyota','toyota tercel');
INSERT INTO CarName VALUES (357,'mazda','mazda glc 4');
INSERT INTO CarName VALUES (358,'plymouth','plymouth horizon 4');
INSERT INTO CarName VALUES (359,'ford','ford escort 4w');
INSERT INTO CarName VALUES (360,'ford','ford escort 2h');
INSERT INTO CarName VALUES (361,'volkswagen','volkswagen jetta');
INSERT INTO CarName VALUES (362,'renault','renault 18i');
INSERT INTO CarName VALUES (363,'honda','honda prelude');
INSERT INTO CarName VALUES (364,'toyota','toyota corolla');
INSERT INTO CarName VALUES (365,'datsun','datsun 200sx');
INSERT INTO CarName VALUES (366,'mazda','mazda 626');
INSERT INTO CarName VALUES (367,'peugeot','peugeot 505s turbo diesel');
INSERT INTO CarName VALUES (368,'saab','saab 900s');
INSERT INTO CarName VALUES (369,'volvo','volvo diesel');
INSERT INTO CarName VALUES (370,'toyota','toyota cressida');
INSERT INTO CarName VALUES (371,'datsun','datsun 810 maxima');
INSERT INTO CarName VALUES (372,'buick','buick century');
INSERT INTO CarName VALUES (373,'oldsmobile','oldsmobile cutlass ls');
INSERT INTO CarName VALUES (374,'ford','ford granada gl');
INSERT INTO CarName VALUES (375,'chrysler','chrysler lebaron salon');
INSERT INTO CarName VALUES (376,'chevrolet','chevrolet cavalier');
INSERT INTO CarName VALUES (377,'chevrolet','chevrolet cavalier wagon');
INSERT INTO CarName VALUES (378,'chevrolet','chevrolet cavalier 2-door');
INSERT INTO CarName VALUES (379,'pontiac','pontiac j2000 se hatchback');
INSERT INTO CarName VALUES (380,'dodge','dodge aries se');
INSERT INTO CarName VALUES (381,'pontiac','pontiac phoenix');
INSERT INTO CarName VALUES (382,'ford','ford fairmont futura');
INSERT INTO CarName VALUES (383,'amc','amc concord dl');
INSERT INTO CarName VALUES (384,'volkswagen','volkswagen rabbit l');
INSERT INTO CarName VALUES (385,'mazda','mazda glc custom l');
INSERT INTO CarName VALUES (386,'mazda','mazda glc custom');
INSERT INTO CarName VALUES (387,'plymouth','plymouth horizon miser');
INSERT INTO CarName VALUES (388,'mercury','mercury lynx l');
INSERT INTO CarName VALUES (389,'nissan','nissan stanza xe');
INSERT INTO CarName VALUES (390,'honda','honda accord');
INSERT INTO CarName VALUES (391,'toyota','toyota corolla');
INSERT INTO CarName VALUES (392,'honda','honda civic');
INSERT INTO CarName VALUES (393,'honda','honda civic (auto)');
INSERT INTO CarName VALUES (394,'datsun','datsun 310 gx');
INSERT INTO CarName VALUES (395,'buick','buick century limited');
INSERT INTO CarName VALUES (396,'oldsmobile','oldsmobile cutlass ciera (diesel)');
INSERT INTO CarName VALUES (397,'chrysler','chrysler lebaron medallion');
INSERT INTO CarName VALUES (398,'ford','ford granada l');
INSERT INTO CarName VALUES (399,'toyota','toyota celica gt');
INSERT INTO CarName VALUES (400,'dodge','dodge charger 2.2');
INSERT INTO CarName VALUES (401,'chevrolet','chevrolet camaro');
INSERT INTO CarName VALUES (402,'ford','ford mustang gl');
INSERT INTO CarName VALUES (403,'volkswagen','vw pickup');
INSERT INTO CarName VALUES (404,'dodge','dodge rampage');
INSERT INTO CarName VALUES (405,'ford','ford ranger');
INSERT INTO CarName VALUES (406,'chevrolet','chevy s-10');
